server:
  port: 8082
spring:
  application:
    name: desenvolvedora-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:desenvolvedora
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
